version: "3.8"

services:
  whatsaly:
    build: .
    container_name: whatsaly-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: whatsaly-redis
    ports:
      - "6379:6379"
    restart: always
