version: "3.8"

services:
  whatsaly:
    build: .
    container_name: whatsaly-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - NODE_OPTIONS=--max-old-space-size=32
      - BUN_JSC_forceGCSlowPaths=1
      - BUN_JSC_useJIT=0
      - BUN_JSC_gcMaxHeapSize=33554432

  redis:
    image: redis:alpine
    container_name: whatsaly-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 24M
        reservations:
          memory: 16M
