name: Rust CI

on:
  push:
    branches: ["master"]
    paths:
      - "service/**"
      - "util/**"
      - "Cargo.toml"
  pull_request:
    branches: ["master"]
    paths:
      - "service/**"
      - "util/**"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [service, util]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ${{ matrix.project }}

      - name: Check formatting
        run: cargo fmt --all -- --check
        working-directory: ./${{ matrix.project }}

      - name: Run clippy
        run: cargo clippy -- -D warnings
        working-directory: ./${{ matrix.project }}

      - name: Run tests
        run: cargo test
        working-directory: ./${{ matrix.project }}
